### ISSUE TITLE
Reduce amount of CI tasks

### ISSUE THREAD

**Issue by fkorotkov** [cjdb/project_template#5]
**Is your feature request related to a problem? Please describe.**

Fraud detection mechanism of Cirrus CI is triggering on this repo. It thinks you mine some crypto coins. 😅 

**Describe the solution you'd like**

Two possible things come to mind:

1. Combine some of the tasks if possible to reduce overall CPU footprint of a single change. Two matrixes which results in **38 tasks** with 4 cores for each change.
2. Maybe run only a few configurations for PRs and all for master branch? Do you really need both Release and Debug?

/cc @cjdb

**Comment by cjdb** [comment]
> Fraud detection mechanism of Cirrus CI is triggering on this repo. It thinks you mine some crypto coins. 😅

Oh dear. That's not good. Thanks for reporting this! 😄 

> Combine some of the tasks if possible to reduce overall CPU footprint of a single change. Two matrixes which results in *38 tasks* with 4 cores for each change.

I think this is the preferred option, but I might need some help.

This is a project template, which I'm planning to use as a starter for other projects. I can dial down the number of cores on this project to 2 (if it's still a resource sink, I can go to 1, but I'd rather have two to show that parallel building is working). This project is rather cheap to build: it only has a few CMakeLists.txt and a few C++ regression tests. The CI is designed to prove that all of the configurations are supported, so that derivative projects can choose what is appropriate for them. Derivative projects _will_ be significantly more expensive to build, and might even benefit from using all eight cores across everything that I plan to support (I still need to add support for Windows, Windows using MinGW, and Mac OS). That is beyond my control, but I'm open to looking into ways to lead by example here, which is what my `.cirrus.yml` is intended to serve as.

Both debug and release builds are necessary, so I'll combine those, to halve the number of jobs created. I'll also leave this open until the remaining platforms are added: can you please keep me updated on this?

**Comment by fkorotkov** [comment]
I'll whitelist your account in the meantime and will take a closer look a little bit later today. 🙌

**Comment by fkorotkov** [comment]
@cjdb could you please explain to me what affects what *conan* is installing? I noticed that's what takes the most time in CI. I wonder if it's possible to use Docker files to cache an environment with everything pre-installed. Cirrus CI has a [pretty cool feature](https://cirrus-ci.org/guide/docker-builder/#dockerfile-as-a-ci-environment) for that.

**Comment by cjdb** [comment]
Conan installs all of the necessary package dependencies for a project, and is controlled by the top-level file [conanfile.py](https://github.com/cjdb/basic_project/blob/cirrus-2/conanfile.py#L27).

The packages need to be installed once per toolchain, per build type (so GCC 8 Debug and GCC 8 Release are treated independently). I don't know if it's possible for this to be effectively cached, but I'll look into it.

**Comment by cjdb** [comment]
@fkorotkov I think I have worked out why `conan install` is taking so long. After some light investigation, it seems that only the `clang-8*` profiles are taking extreme amounts of time to install, and this is likely due to the fact that one or many of the packages haven't yet been built remotely for Clang 8: the install component is instructed to build any missing binaries, and given the amount of time taken to install, I'm wagering that the Boost libraries are what's chewing up time. For the record, LLVM 8 is still bleeding-edge: it hasn't even been officially released yet, so this is not surprising after having thought about it.

I see a few options to minimise the amount of time spent building libraries until this is fixed upstream:

1. Do nothing, bear the cost for now. This doesn't impact me that much, but it might have ramifications for other users.
2. Use eight CPUs to build. This will temporarily strain the system (does 19 jobs * 8 cores cause the same problem as 38 jobs * 4 cores?), but will also theoretically cut the total amount of time spent using Cirrus hardware from eight minutes to four minutes.
   1. Is it possible to have only certain jobs be spun up with eight cores? If just those three can go to eight cores, then it might be okay.

**Comment by fkorotkov** [comment]
@cjdb I think #6 did the job of reducing the overall amount of CPU minutes. The fraud detection is checking for overall amount of CPU minutes: 8 cores for 1 minute is equal to 2 cores for 4 from that perspective. So if you don't have 4x time reduction then it's kind of doesn't make too much sense.

Thank you so much for addressing the concerns! 🙌

**Comment by cjdb** [comment]
> I wonder if it's possible to use Docker files to cache an environment with everything pre-installed. Cirrus CI has a pretty cool feature for that.

Thanks for putting this on my radar @fkorotkov! I've just made a PR to a different project so that it's easier to update CI! 🙌
